apiVersion: apps/v1
kind: Deployment
metadata:
  name: vcube-deployment
  labels:
    app: vcube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vcube
  template:
    metadata:
      labels:
        app: vcube
    spec:
      containers:
        - name: vcube-app
          image: krishnamohan2004/python:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
              name: http
          env:
            - name: DATA_DIR
              value: "/app/data"
          volumeMounts:
            - name: vcube-storage
              mountPath: "/app/data"
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
      volumes:
        - name: vcube-storage
          persistentVolumeClaim:
            claimName: vcube-data-pvc
